# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(676, 573)
        MainWindow.setStyleSheet("background: gray")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 661, 191))
        self.textEdit.setStyleSheet("font: 10pt \"MS Serif\";\n"
"border: 2px solid white;")
        self.textEdit.setObjectName("textEdit")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 240, 361, 221))
        self.listWidget.setStyleSheet("font: 10pt \"MS Serif\";\n"
"border: 2px solid white;")
        self.listWidget.setObjectName("listWidget")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(380, 240, 291, 171))
        self.listWidget_2.setStyleSheet("font: 10pt \"MS Serif\";\n"
"border: 2px solid white;")
        self.listWidget_2.setObjectName("listWidget_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 470, 121, 23))
        self.pushButton.setStyleSheet("font: 10pt \"MS Serif\";\n"
"background: black;\n"
"color: white;\n"
"border: 2px solid white;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 470, 111, 23))
        self.pushButton_2.setStyleSheet("font: 10pt \"MS Serif\";\n"
"border: 2px solid white;\n"
"background: black;\n"
"color: white;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 470, 111, 23))
        self.pushButton_3.setStyleSheet("font: 10pt \"MS Serif\";\n"
"background: black;\n"
"color: white;\n"
"border: 2px solid white;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(380, 420, 291, 41))
        self.lineEdit.setStyleSheet("font: 12pt \"MS Serif\";")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(380, 470, 131, 23))
        self.pushButton_4.setStyleSheet("font: 10pt \"MS Serif\";\n"
"background: black;\n"
"color: white;\n"
"border: 2px solid white;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(520, 470, 151, 23))
        self.pushButton_5.setStyleSheet("font: 10pt \"MS Serif\";\n"
"background: black;\n"
"color: white;\n"
"border: 2px solid white;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(380, 500, 291, 23))
        self.pushButton_6.setStyleSheet("font: 10pt \"MS Serif\";\n"
"background: black;\n"
"color: white;\n"
"border: 2px solid white;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 220, 121, 16))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 12pt \"MS Serif\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(380, 220, 101, 16))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 12pt \"MS Serif\";")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 676, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Створити"))
        self.pushButton_2.setText(_translate("MainWindow", "Видалити"))
        self.pushButton_3.setText(_translate("MainWindow", "Зберегти"))
        self.lineEdit.setText(_translate("MainWindow", "Введіть тег..."))
        self.pushButton_4.setText(_translate("MainWindow", "Додати тег до замітки"))
        self.pushButton_5.setText(_translate("MainWindow", "Відкрипити тег від замітки"))
        self.pushButton_6.setText(_translate("MainWindow", "Шукати замітки по тегу"))
        self.label.setText(_translate("MainWindow", "Список заміток"))
        self.label_2.setText(_translate("MainWindow", "Список тегів"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
